### ISSUE TITLE
Improvements

### ISSUE THREAD

**Issue by lsiepel** [seaside1/unifiprotect#10]
Really like this binding. It is also popular in the marketplace :-)

Earlier i made a PR to improve the readme. Now that i use the binding for a day or so i had some unexpected memmory issues i never had before. Might not be related to this binding, but anyway i pulled the sources and did some code checking. The code looks code, but i also see some room for improvement.
Today i spend some time to do some minor refactoring, added background scans. I think this benefits the overall code quality. Once i finish working i'll make a PR for that too if you are interested.

**Comment by lsiepel** [comment]
Gentle ping @seaside1

**Comment by seaside1** [comment]
Sure why not. I opted out of background scan just to not have it running unless you really want it to, but then again background scanning is done in a lot of bindings.
If you want background scanning and submit a PR for it, I will merge it as long as it is working ok. Any improvements to the code is more than welcome!
BR S

**Comment by seaside1** [comment]
Closing, feel free to submit a PR.
