### ISSUE TITLE
Feature request: Privacy mode zone enabling/disabling

### ISSUE THREAD

**Issue by seime** [seaside1/unifiprotect#13]
Since the Unifi cameras cannot be switched off, a workaround is to add a camera privacy zone which then is enabled/disabled on demand.

See details here; https://community.ui.com/questions/Temporarily-disable-camera/80a3b563-283f-48c5-852d-6e61a08a7bc0#answer/0bc4a45b-2411-4f5d-8164-f3250384b084

**Comment by seaside1** [comment]
Good suggestion.  Should be possible to add.

Other possible workarounds:
- Change recording mode on camera to off (you can see but at least not recording)
- If you power the camera with poe, you can turn it off by cutting power, I do this with a binding / script in my automations.

**Comment by seime** [comment]
I've implemented disabling of recording already, but the WAF was still well below freezing 🧊 . And most cameras are connected via a non-unifi switch which I cannot manage :(

**Comment by seaside1** [comment]
What switch are you using? I'm not using a UniFi swith either. I have Juniper Ex3300, which I can login to via cli and shutdown poe. I have a quite simple bash script I invoke from openHAB that can toggle PoE on / off.

**Comment by seime** [comment]
It is a Netgear GS108PEv3, but it does not support SNMP nor REST. My other options seems to be either to  attempt wrapping https://github.com/TheGreyDiamond/PyNetgearSwitchController (did not work) or write my own webscraper in JRule. Which feels like a stretch ;)

**Comment by seaside1** [comment]
@seime 
I have implemented this now see: https://github.com/seaside1/unifiprotect/commit/89e9d3542321b373e5b99cd5dc565bc0c8ebbbca

You have to compile the jar yourself if you want to test. Will build the next version as soon as I have added support for turning chime off on doorbell.

**Comment by seime** [comment]
Thanks @seaside1 , confirmed working well :)

**Comment by seaside1** [comment]
Great!  Thanks for testing it out.
