### ISSUE TITLE
Is-ringing item not triggered anymore after upgrade to OH4.0

### ISSUE THREAD

**Issue by LeoVe** [seaside1/unifiprotect#15]
We performed the upgrade to OH4.0, unfortunately the doorbell ringing is no longer triggered.

The status of all of the Unifi things is ONLINE though. No log entries of pushing the doorbell.

**Comment by lsiepel** [comment]
What versions do you have? I have openHAB 4.0.1, g4 doorbell and binding org.openhab.binding.unifiprotect-4.0.0-BETA10
All functional.

**Comment by LeoVe** [comment]
Hi lsiepel,

Thanks for your reply!

We have openhab 4.0.0 and unifi protect v 3.x.x (I think).

How did you install unifi protect 4.0.0 beta?

**Comment by lsiepel** [comment]
https://github.com/seaside1/unifiprotect/releases

**Comment by LeoVe** [comment]
Thx !!

**Comment by LeoVe** [comment]
Hi lsiepel,

The Beta does the trick, it works again!

Thank you 👍
