### ISSUE TITLE
status-sound

### ISSUE THREAD

**Issue by lsiepel** [seaside1/unifiprotect#16]
What is the purpose of the unifiprotect:g4doorbell:NVRID:buiten_voorkant_deurbel:status-sounds channel?

I thought that when turned off, the chime is is not ringing after pressing the doorbell. But when the doorbell is pressed, the chime is making sounds and the channel just turns on again.
Is this a bug has the channel a different usage?

**Comment by seaside1** [comment]
Stauts sounds is more related to status not doorbell chime, like for instance if the camera goes offline, comes online or something else. It is the same thing you have in the UI

![Screenshot from 2023-09-17 19-54-36](https://github.com/seaside1/unifiprotect/assets/24649305/dae343dc-5fd6-48da-bbf4-4d344872377d)

**Comment by seaside1** [comment]
I will add a channel for turning chime off on the doorbell. It is very useful to be able to do that when the kids are sleeping.

**Comment by seaside1** [comment]
@lsiepel  I have added otpion to turn on and off chime.
https://github.com/seaside1/unifiprotect/releases/tag/unifiprotect-4.0.0-v1.1

**Comment by lsiepel** [comment]
Gonna try that, really great!
