### ISSUE TITLE
Full example doesn't include Bridge sample

### ISSUE THREAD

**Issue by jpalo** [seaside1/unifiprotect#2]
Could you please add bridge sample, as the documentation doesn't contain property names of the required Bridge configuration options.

**Comment by seaside1** [comment]
Hi!

Are you using OpenHAB 2 or OpenHAB 3?
I'm not using a manual bridge configuration myself, the recommended approach is to add the bridge using 
PaperUI for Openhab2 and regular GUI for OpenHAB 3. 

If you think it is needed I can try and see if I can get a manual setup of the bridge going.

/S

**Comment by jpalo** [comment]
Just to conclude this, here is a working Bridge sample

```
Bridge unifiprotect:nvr:6477f4613d "UniFi Protect" [ host="...", username="...", password="...", refresh=60 ] {
   Thing camera frontDoorCamera [name="Front door camera", mac="12:12:12:12:12:12"]
}
```
