### ISSUE TITLE
Installation via Marketplace not working

### ISSUE THREAD

**Issue by mheiss** [seaside1/unifiprotect#22]
I noticed that the addon was missing after the latest OpenHAB update to 4.1.2 (minor upgrade from 4.1.1) which i installed today. When i then tried to install the addon via marketplace i just get a little popup that states "Addon Installation Failed" no additional information and no additional logs are provided.

Manual installation by dropping the JAR into the addons file-share worked.
Not sure if this or the openhab/addons project is the correct place to report this issue :)

**Comment by seaside1** [comment]
Thanks for reporting. Marketplace now requires a new file name for a new release, I'll fix it in the upcoming releases

**Comment by seaside1** [comment]
Last release used specific name for the release, should work now.
