### ISSUE TITLE
Doorbel Custom Message not showing on LCD screen

### ISSUE THREAD

**Issue by ThaDaVos** [seaside1/unifiprotect#7]
I am messing around with the options you gave me - one of them is the custom LCD message - but it seems to not be updating - at least, I am not seeing it on the LCD screen - and the NVR's settings for the camera's custom display sometimes show a broken select (no options selected) - maybe the key for the option has changed?

**Comment by seaside1** [comment]
I'm out traveling, can investigate this in a week when I have access to a doorbell

**Comment by ThaDaVos** [comment]
And, did you have time to look at it?

Also, the disconnects still happen

**Comment by seaside1** [comment]
Thanks for the bump. Going to give this project some prio, but have not been able to work on it lately.

**Comment by ThaDaVos** [comment]
@seaside1 - any progress on this?
I just installed the latest binding version but I don't see any mention of it in the release notes (haven't checked it yet though)

**Comment by seaside1** [comment]
Not fixed yet. I guess first thing is to decide how to handle the custom doorbell message in the thing config vs using the one in the channel.

So now there is a channel for displaying custom text it will be triggered when you click on the enable custom message button.
If the thing config contains a custom message it will override whatever is sent in the channel.

I'm thinking of chaging the solution to:
- As soon as the custom message channel receives a value it will be displayed directly on the lcd (without the need for it being toggled with a button) that message will be stored in the thing config as well so it will be visible if you want to configure it in the gui.

**Comment by ThaDaVos** [comment]
That's a great idea! I noticed when I set it now (I've found a way to create a text input on it) and toggle the `Show Custom Message` channel - after a while it just changes back, just as if it's never sent to the doorbell itself

**Comment by seaside1** [comment]
This is fixed in BETA7
