### ISSUE TITLE
Items wont be updated

### ISSUE THREAD

**Issue by mryshakow** [seaside1/unifiprotect#8]
First of all: Great work - Thank you!

Unfortunately, my item values remain at null. I use the following configuration:

Things: 
`Bridge unifiprotect:nvr:home "UniFi Protect NVR" [ host="192.168.1.1", username="username", password="password", refresh=60 ] {
   Thing g3camera frontDoorCamera [name="Front door camera", mac="11:A1:11:1A:A1:11"]
}`

Example for items:

`String   g3FrontDoorName             "Front Door Cam Name"                                             (g3FrontDoor) { channel="unifiprotect:g3camera:home:frontDoorCamera:name" }`

In the UI, both the Bridge and the Camera are "online". Any idea?

**Comment by mryshakow** [comment]
I guess a little bit of context could be nice...:


Openhabian: OpenHAB 3.3.0
Unifi DM Pro: UnifiOS 1.12.33, Protect 2.2.6

**Comment by seaside1** [comment]
To avoid errors try adding the things in the ui  and see if that works better. Make sure you can login the credentials as well. 

If that does not work you need to enable debug log so we can see what's going on.

**Comment by seaside1** [comment]
Closing since there has been no feedback.
